export type ChainEvent =
  | { date: string; type: 'noticed' | 'notice' | 'response' | 'fail' | 'inspect'; lbl: string; c: string }
  | { type: 'gap'; lbl: string; c: string };

export type Evidence = {
  tp: string;
  id: string;
  bates: string;
  desc: string;
  c: string;
};

export type Defect = {
  id: string;
  bates: string;
  color: string;
  hex: number;
  typeLbl: string;
  sev: string;
  sevCls: 'si' | 'sm' | 'ss';
  room: string;
  code: string;
  threshold: string;
  found: string;
  area: string;
  pos: [number, number, number];
  gap: number;
  reported: string;
  status: string;
  lab: string;
  narr: string;
  contra: string | null;
  pun: string;
  punCls: 'pc' | 'ph' | 'pm';
  punTxt: string;
  dmg: string;
  chain: ChainEvent[];
  evidence: Evidence[];
};

export const DEFECTS: Defect[] = [
  {
    id: 'MOLD-001', bates: 'PLNT000234–241', color: '#22c55e', hex: 0x22c55e,
    typeLbl: 'Mold — Confirmed Aspergillus niger (laboratory)', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'Bathroom (NW) — ceiling + north wall', code: 'CA H&S §17920.3(a)(13)',
    threshold: '10,000 spores/m³', found: '48,000 spores/m³ — 4.8× threshold', area: '38 sq ft',
    pos: [-2.4, 2.82, -3.15], gap: 71, reported: '2024-01-03', status: 'UNREMEDIATED',
    lab: 'Aspergillus niger confirmed — 48,000 spores/m³. Actionable threshold: 10,000. Exceedance 4.8×. Area: 38 sq ft (ceiling) + 14" wall extension. Minor child sleeps in adjacent bedroom.',
    narr: 'Mold colony NE quadrant of bathroom ceiling, extending 14" down north wall. Confirmed Aspergillus niger. Certified-letter notice Jan 3, 2024. No remediation as of Mar 15 inspection — 71 days elapsed.',
    contra: '⚑ CONTRADICTION: Maintenance log (DFND000445) claims "mold remediation completed Feb 2, 2024." Mar 15 lab report confirms zero remediation. Inspector: no evidence of any work performed.',
    pun: 'HIGH', punCls: 'ph', punTxt: '3 notices + 71-day gap + false completion claim = willful/oppressive conduct (CC §3294).',
    dmg: '$380,000',
    chain: [
      { date: '2023-11-15', type: 'noticed', lbl: 'Tenant first observes mold growth', c: '#22c55e' },
      { date: '2024-01-03', type: 'notice', lbl: 'Certified letter sent to landlord', c: '#4b8df8' },
      { date: '2024-01-10', type: 'response', lbl: '"We\'ll look into it" — PM email', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO ACTION — 71 DAYS ELAPSED', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Expert: zero remediation confirmed', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'LAB', id: 'LAB-2024-0315-01', bates: 'PLNT000234–239', desc: 'Air quality lab — Aspergillus niger confirmed', c: '#22c55e' },
      { tp: 'PHO', id: 'PHO-2024-0315-47', bates: 'PLNT000240–241', desc: 'EXIF-verified RAW photography — ceiling colony', c: '#4b8df8' },
      { tp: 'LTR', id: 'LTR-2024-0103', bates: 'PLNT000189', desc: 'Certified letter — first written notice', c: '#f59e0b' },
      { tp: 'EML', id: 'EML-2024-0110', bates: 'DFND000312', desc: 'PM email response — "will look into it"', c: '#f59e0b' },
      { tp: 'LOG', id: 'LOG-DFND-445', bates: 'DFND000445', desc: '⚑ Maintenance log claiming Feb 2 completion — CONTRADICTED', c: '#dc4f35' },
    ],
  },
  {
    id: 'WATER-001', bates: 'PLNT000189–201', color: '#4b8df8', hex: 0x4b8df8,
    typeLbl: 'Water intrusion — active (failed roof membrane at parapet)', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'Bedroom (NE) — north wall, upper zone (above bed)', code: 'CA Civ. Code §1941.1(a)(4)',
    threshold: '19% WME', found: '42% WME — active seepage', area: '18 sq ft stain · wall cavity compromised',
    pos: [1.6, 1.88, -3.92], gap: 116, reported: '2023-11-20', status: 'ATTEMPTED — FAILED ×2',
    lab: 'Moisture meter: 42% WME at 3 points (threshold: 19%). Source: failed roof membrane at parapet junction directly above unit. Borescope (PLNT000199): nascent Cladosporium colony forming in stud cavity. BED IS DIRECTLY BELOW INTRUSION POINT.',
    narr: 'Active water seepage through north bedroom wall. Staining 6ft × 3ft. Two failed repair attempts (Dec 4, Jan 22). Borescope confirms mold forming in wall cavity. Occupants sleep directly below active leak.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: 'Two documented failed repair attempts establish constructive knowledge + failure to cure.',
    dmg: '$210,000',
    chain: [
      { date: '2023-10-08', type: 'noticed', lbl: 'Seepage first observed', c: '#22c55e' },
      { date: '2023-11-20', type: 'notice', lbl: 'Written notice to property manager', c: '#4b8df8' },
      { date: '2023-11-28', type: 'response', lbl: 'PM dispatches roofer — first attempt', c: '#f59e0b' },
      { date: '2023-12-04', type: 'fail', lbl: 'Repair attempt #1 — FAILED (leaked same night)', c: '#dc4f35' },
      { date: '2024-01-22', type: 'fail', lbl: 'Repair attempt #2 — FAILED (borescope confirms)', c: '#dc4f35' },
      { type: 'gap', lbl: 'NO FURTHER ACTION — 52 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Expert: active leak + cavity mold confirmed', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'RDR', id: 'RDR-2024-0315-01', bates: 'PLNT000189–193', desc: 'Moisture meter data — 12 readings, 3 locations', c: '#4b8df8' },
      { tp: 'BOR', id: 'BOR-2024-0315-01', bates: 'PLNT000194–199', desc: 'Borescope video — wall cavity mold growth', c: '#22c55e' },
      { tp: 'PHO', id: 'PHO-2024-0315-28', bates: 'PLNT000200–201', desc: 'EXIF-verified stain documentation (GPS-tagged)', c: '#4b8df8' },
      { tp: 'INV', id: 'INV-CNTR-2023-12', bates: 'DFND000388', desc: 'Roofing contractor invoice — failed repair Dec 4', c: '#f59e0b' },
    ],
  },
  {
    id: 'HVAC-001', bates: 'PLNT000302–309', color: '#f59e0b', hex: 0xf59e0b,
    typeLbl: 'HVAC failure — heating system non-functional (all habitable rooms)', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'All habitable rooms — living 58°F · bedroom 54°F · kitchen 61°F', code: 'CA Civ. Code §1941.1(a)(6)',
    threshold: '70°F at 3 ft AFF', found: '54–61°F across all rooms — 9–16°F below threshold', area: 'Est. 780 sq ft (all habitable)',
    pos: [-1.4, 2.88, 1.8], gap: 43, reported: '2023-12-03', status: 'UNREMEDIATED',
    lab: 'Temp at 3ft AFF: Living 58°F, Bedroom 54°F, Kitchen 61°F. Statutory min 70°F. Data logger (PLNT000307): 14 consecutive nights below 60°F Dec 2023. Subpoena: NO work order was ever issued by landlord.',
    narr: 'Central heating non-functional. All rooms 9–16°F below statutory minimum. PM claimed "looking into it" Dec 5 but issued no work order. Minor child (age 4) exposed to sustained sub-60°F conditions.',
    contra: '⚑ CONTRADICTION: PM email (DFND000312) states "heating system is fully operational." Data logger records 14 consecutive sub-60°F nights during the same period.',
    pun: 'HIGH', punCls: 'ph', punTxt: 'Non-repair after notice + affirmative false claim of functionality = willful/fraudulent conduct (CC §3294).',
    dmg: '$95,000 + habitability diminution ×3 mo.',
    chain: [
      { date: '2023-11-30', type: 'noticed', lbl: 'Tenant notices heating failure', c: '#22c55e' },
      { date: '2023-12-03', type: 'notice', lbl: 'Written notice to PM', c: '#4b8df8' },
      { date: '2023-12-05', type: 'response', lbl: 'PM: "looking into it" — no work order issued', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO REPAIR — 43 DAYS ELAPSED', c: '#dc4f35' },
      { date: '2024-01-15', type: 'inspect', lbl: 'Expert inspection: all rooms below 70°F', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'LOG', id: 'LOG-TEMP-DEC23', bates: 'PLNT000302–307', desc: 'Temperature data logger — 14 nights below 60°F', c: '#f59e0b' },
      { tp: 'EML', id: 'EML-2023-1205', bates: 'DFND000312', desc: '⚑ PM email: "fully operational" — CONTRADICTED', c: '#dc4f35' },
      { tp: 'SUB', id: 'SUB-WORKORDERS', bates: 'DFND000401–408', desc: 'Subpoena return: no HVAC work order ever issued', c: '#8b5cf6' },
    ],
  },
  {
    id: 'CRACK-001', bates: 'PLNT000156–171', color: '#dc4f35', hex: 0xdc4f35,
    typeLbl: 'Structural — diagonal shear crack (south wall, window sill to floor)', sev: 'SIGNIFICANT', sevCls: 'ss',
    room: 'Living room (SW) — south wall · crack propagating +8" over 6 months', code: 'IBC §1604.3 / CA H&S §17920.3(a)(1)',
    threshold: '1.5 mm (IBC investigation)', found: '3.2 mm — 2.1× threshold · 45° diagonal trajectory', area: '62 in. length · growing 1.3 in/month',
    pos: [-0.45, 1.38, 3.92], gap: 182, reported: '2023-09-14', status: 'UNREMEDIATED',
    lab: 'Crack width 3.2 mm (IBC threshold 1.5 mm, exceedance 2.1×). Trajectory: 45° diagonal consistent with differential foundation settlement. Photogrammetric series: +8 inches growth over 6 months (EXIF-timestamped RAW, PLNT000160–165).',
    narr: 'Diagonal shear crack from window sill to floor. PM classified as "cosmetic" — expert confirms structural. Growing crack consistent with foundation settlement. 182 days unremediated.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: '182 days unremediated + PM misclassification as cosmetic + growing crack = constructive knowledge of structural risk.',
    dmg: '$185,000',
    chain: [
      { date: '2023-09-14', type: 'noticed', lbl: 'Tenant notices crack — notifies PM same day', c: '#22c55e' },
      { date: '2023-10-01', type: 'response', lbl: 'PM: "cosmetic only, normal settlement"', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO INSPECTION OR REPAIR — 182 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Expert: structural — IBC threshold exceeded, growing', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'PHO', id: 'PHO-CRACK-SERIES', bates: 'PLNT000160–165', desc: 'Photogrammetric RAW series — 6-date propagation record', c: '#dc4f35' },
      { tp: 'STR', id: 'STR-RPT-2024-03', bates: 'PLNT000166–171', desc: 'Structural engineering expert report', c: '#dc4f35' },
      { tp: 'EML', id: 'EML-PM-2023-1001', bates: 'DFND000356', desc: 'PM email: "cosmetic — normal settlement" — disputed', c: '#f59e0b' },
    ],
  },
  {
    id: 'LEAD-001', bates: 'PLNT000089–104', color: '#e060a0', hex: 0xe060a0,
    typeLbl: 'Lead paint — hazardous, FRIABLE (kitchen east wall + hallway)', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Kitchen (SE) + hallway — east wall · minor child age 4 occupies unit', code: '40 CFR Part 745 · CA H&S §17920.3(a)(9) · 42 U.S.C. §4852d',
    threshold: '1.0 mg/cm² (EPA)', found: '2.4 mg/cm² — 2.4× threshold · FRIABLE condition', area: '~140 sq ft kitchen east wall + hallway',
    pos: [4.18, 1.05, 2.15], gap: 226, reported: '2023-08-01', status: 'UNREMEDIATED',
    lab: 'XRF: 2.4 mg/cm² (EPA threshold 1.0 mg/cm², exceedance 2.4×). FRIABLE — active chip-off. 1962 construction — federal disclosure mandatory. Occupant: minor child age 4 (elevated blood-lead vulnerability, CDC). FEDERAL STATUTE VIOLATION confirmed.',
    narr: 'Lead paint at 2.4× EPA threshold throughout kitchen/hallway east wall. Friable, deteriorating. Minor child occupies unit. Building 1962. Landlord affirmatively denied knowledge. 226 days unremediated. Federal treble damages triggered.',
    contra: '⚑ CONTRADICTION: Landlord disclosure (DFND000089) states "No known lead hazard." Building records confirm 1962 construction — constructive knowledge legally implied. XRF confirms 2.4 mg/cm². Federal violation: 42 U.S.C. §4852d — mandatory treble damages.',
    pun: 'CRITICAL', punCls: 'pc', punTxt: 'Federal disclosure violation + minor in unit + affirmative denial + 226 days = CRITICAL. Treble damages mandatory under 42 U.S.C. §4852d.',
    dmg: '$1,977,500 (incl. federal treble)',
    chain: [
      { date: '2023-08-01', type: 'noticed', lbl: 'Tenant requests lead test — minor child in unit', c: '#22c55e' },
      { date: '2023-08-01', type: 'notice', lbl: 'Written notice + disclosure request to PM', c: '#4b8df8' },
      { date: '2023-08-15', type: 'response', lbl: 'PM written response: "no known lead hazard"', c: '#dc4f35' },
      { type: 'gap', lbl: 'NO ABATEMENT — 226 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'XRF confirms 2.4 mg/cm² — FEDERAL VIOLATION', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'XRF', id: 'XRF-2024-0315-01', bates: 'PLNT000089–094', desc: 'XRF lead paint analysis — 2.4 mg/cm² confirmed', c: '#e060a0' },
      { tp: 'DIS', id: 'DIS-LL-2023-0815', bates: 'DFND000089', desc: '⚑ Landlord disclosure: "no known lead" — CONTRADICTED', c: '#dc4f35' },
      { tp: 'MED', id: 'MED-CHILD-BLL-01', bates: 'PLNT000095–099', desc: 'Minor child blood lead level test — elevated', c: '#e060a0' },
      { tp: 'BLD', id: 'BLD-RECORDS-1962', bates: 'PLNT000100–104', desc: 'Building records — 1962 construction, constructive knowledge', c: '#8b5cf6' },
      { tp: 'FED', id: 'FED-4852D', bates: 'PLNT000090', desc: 'Federal violation analysis — 42 U.S.C. §4852d treble damages', c: '#dc4f35' },
    ],
  },
  {
    id: 'ASBE-001', bates: 'PLNT000412–428', color: '#a78bfa', hex: 0xa78bfa,
    typeLbl: 'Asbestos — friable thermal pipe insulation (utility chase)', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Utility chase (central) · disturbed during failed Dec 2023 repair', code: '40 CFR Part 61 Subpart M · Cal/OSHA §1529',
    threshold: '0.1 f/cc (PEL · 8-hr TWA)', found: '0.42 f/cc — 4.2× PEL · friable chrysotile', area: '11 linear ft of pipe wrap',
    pos: [0.6, 2.55, -0.2], gap: 89, reported: '2023-12-18', status: 'UNREMEDIATED · ACCESS RESTRICTED',
    lab: 'PLM analysis: 18% chrysotile asbestos in friable pipe-wrap insulation. Air sample post-disturbance: 0.42 f/cc (8× background). Disturbance event during HVAC repair attempt Dec 4, 2023 — performed without abatement protocols. Building age 1962 — pre-ban material consistent.',
    narr: 'Chrysotile asbestos disturbed by unlicensed contractor during failed HVAC repair. No NESHAP notification filed. Air monitoring confirms ongoing fiber release into return-air plenum serving all habitable rooms. Federal abatement required.',
    contra: '⚑ CONTRADICTION: Contractor invoice (DFND000388) describes work as "minor pipe insulation replacement" — no mention of suspect ACM. NESHAP 10-day pre-notification (40 CFR §61.145) was never filed. Strict-liability federal violation.',
    pun: 'CRITICAL', punCls: 'pc', punTxt: 'Strict-liability federal NESHAP violation + return-air contamination + minor in unit = CRITICAL exposure. EPA penalties up to $109,024/day per violation.',
    dmg: '$640,000',
    chain: [
      { date: '2023-12-04', type: 'fail', lbl: 'Disturbance event — HVAC contractor cuts pipe wrap', c: '#dc4f35' },
      { date: '2023-12-18', type: 'noticed', lbl: 'Tenant notices white fiber dust on HVAC vents', c: '#22c55e' },
      { date: '2023-12-19', type: 'notice', lbl: 'Written notice + lab request to PM', c: '#4b8df8' },
      { type: 'gap', lbl: 'NO ABATEMENT · NO NESHAP FILING — 89 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'PLM + air monitoring confirms friable chrysotile', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'PLM', id: 'PLM-2024-0315-04', bates: 'PLNT000412–417', desc: 'Polarized light microscopy — 18% chrysotile confirmed', c: '#a78bfa' },
      { tp: 'AIR', id: 'AIR-2024-0315-02', bates: 'PLNT000418–422', desc: 'Air monitoring — 0.42 f/cc (4.2× PEL)', c: '#a78bfa' },
      { tp: 'INV', id: 'INV-CNTR-2023-12', bates: 'DFND000388', desc: '⚑ Contractor invoice — no ACM disclosure (NESHAP violation)', c: '#dc4f35' },
      { tp: 'FED', id: 'FED-NESHAP', bates: 'PLNT000423–428', desc: 'Federal NESHAP §61.145 non-notification analysis', c: '#dc4f35' },
    ],
  },
  {
    id: 'ELEC-001', bates: 'PLNT000501–518', color: '#fb7185', hex: 0xfb7185,
    typeLbl: 'Electrical — knob-and-tube splices in concealed kitchen ceiling', sev: 'SIGNIFICANT', sevCls: 'ss',
    room: 'Kitchen (SE) — concealed ceiling junction · adjacent to lead paint zone', code: 'NEC §394.12 · CA Elec. Code §110.14 · CFC §605.1',
    threshold: 'Splices forbidden in concealed locations (NEC §394.30)', found: '7 unlisted splices · scorch marks · 142°F at junction', area: '4 sq ft of ceiling cavity',
    pos: [3.5, 2.85, 1.2], gap: 54, reported: '2024-01-21', status: 'UNREMEDIATED · ACTIVE FIRE RISK',
    lab: 'Thermographic survey: junction box reads 142°F under 60% rated load. 7 unlisted splices (wire-nut + tape) in concealed location — prohibited by NEC §394.30(B). Scorch marks on adjacent joist. Estimated ignition probability under sustained load: elevated.',
    narr: 'Concealed knob-and-tube splices in kitchen ceiling cavity show active heat signature and char. Modern circuit loads (microwave + dishwasher) exceed safe capacity. Fire-marshal-grade hazard directly above lead-paint deteriorating zone.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: 'Active fire risk + scorch evidence + 54-day non-response = constructive knowledge of imminent ignition risk.',
    dmg: '$155,000',
    chain: [
      { date: '2024-01-19', type: 'noticed', lbl: 'Tenant reports flickering + burning odor', c: '#22c55e' },
      { date: '2024-01-21', type: 'notice', lbl: 'Written notice w/ photos to PM', c: '#4b8df8' },
      { date: '2024-01-25', type: 'response', lbl: 'PM: "scheduling electrician" — no follow-up', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO ELECTRICIAN DISPATCHED — 54 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'IR thermography confirms 142°F at concealed junction', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'IRT', id: 'IRT-2024-0315-07', bates: 'PLNT000501–506', desc: 'IR thermography — 142°F at concealed junction', c: '#fb7185' },
      { tp: 'PHO', id: 'PHO-2024-0315-62', bates: 'PLNT000507–512', desc: 'Borescope photos — scorch marks + 7 unlisted splices', c: '#4b8df8' },
      { tp: 'EML', id: 'EML-2024-0125', bates: 'DFND000522', desc: 'PM email: "scheduling electrician" — no follow-up', c: '#f59e0b' },
      { tp: 'STR', id: 'STR-NEC-394', bates: 'PLNT000513–518', desc: 'NEC §394.30 / CA Elec. Code §110.14 violation memo', c: '#dc4f35' },
    ],
  },
  {
    id: 'PLMB-001', bates: 'PLNT000601–615', color: '#38bdf8', hex: 0x38bdf8,
    typeLbl: 'Plumbing — sewage backflow at kitchen base cabinet (gray + black water)', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Kitchen (SE) — base cabinet · sub-floor saturation', code: 'UPC §710.1 · CA H&S §17920.3(a)(11) · CDC bio-hazard cat. III',
    threshold: '0 cfu/100 mL (potable adjacency)', found: '1.4 × 10⁶ cfu/100 mL coliform · ATP 9,800 RLU',
    area: '11 sq ft cabinet floor + 22 sq ft sub-floor wick',
    pos: [3.9, 0.18, 2.6], gap: 38, reported: '2024-02-06', status: 'UNREMEDIATED · BIOHAZARD POSTED',
    lab: 'Backflow event during municipal main surge Feb 5, 2024. Coliform 1.4×10⁶ cfu/100 mL (potable threshold: 0). ATP swab: 9,800 RLU (food-prep limit: 30). Sub-floor moisture wick measured at 22 sq ft via thermal + moisture mapping. Class 3 IICRC water loss.',
    narr: 'Sewage backflow saturated kitchen base cabinet and sub-floor. PM dispatched a non-IICRC contractor who removed visible water but left contamination in cavity. Bio-aerosols measured in adjacent breathing zone. Food preparation surface 38" away.',
    contra: '⚑ CONTRADICTION: PM service ticket (DFND000612) states "fully sanitized — Cat 1 clean water." Lab confirms Cat 3 black water with active coliform. Misclassification triggers CC §1942.4 + UCL §17200 exposure.',
    pun: 'HIGH', punCls: 'ph', punTxt: 'Affirmative misclassification of Cat 3 → Cat 1 + 38-day non-remediation = willful suppression (CC §3294).',
    dmg: '$295,000',
    chain: [
      { date: '2024-02-05', type: 'fail', lbl: 'Municipal main surge — backflow event', c: '#dc4f35' },
      { date: '2024-02-06', type: 'noticed', lbl: 'Tenant reports sewage odor + standing water', c: '#22c55e' },
      { date: '2024-02-06', type: 'notice', lbl: 'Verbal + written notice (text + email) to PM', c: '#4b8df8' },
      { date: '2024-02-08', type: 'response', lbl: 'Non-IICRC contractor — surface mop only', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO DECONTAMINATION — 38 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'ATP + coliform confirms Cat 3 contamination', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'BIO', id: 'BIO-2024-0315-03', bates: 'PLNT000601–606', desc: 'Coliform culture — 1.4×10⁶ cfu/100 mL', c: '#38bdf8' },
      { tp: 'ATP', id: 'ATP-2024-0315-11', bates: 'PLNT000607–610', desc: 'ATP swab — 9,800 RLU (327× food-prep limit)', c: '#38bdf8' },
      { tp: 'LOG', id: 'LOG-DFND-612', bates: 'DFND000612', desc: '⚑ PM ticket: "Cat 1 clean water" — CONTRADICTED', c: '#dc4f35' },
      { tp: 'PHO', id: 'PHO-2024-0315-71', bates: 'PLNT000611–615', desc: 'Borescope sub-floor cavity — wick + biofilm', c: '#4b8df8' },
    ],
  },
  {
    id: 'LIFE-001', bates: 'PLNT000701–712', color: '#facc15', hex: 0xfacc15,
    typeLbl: 'Life safety — missing/disabled smoke + CO alarms (3 of 4 zones)', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Hallway · Bedroom · Living room — only kitchen unit present (expired 2019)',
    code: 'CA H&S §13113.7 · CRC §R314/R315 · NFPA 72 §29.8',
    threshold: '1 alarm per sleeping room + hallway · CO within 15 ft of sleeping',
    found: '0 functional smoke alarms in sleeping zones · 0 CO alarms unit-wide',
    area: 'Entire 780 sq ft unit',
    pos: [0.2, 2.95, 0.4], gap: 412, reported: '2023-01-29', status: 'UNREMEDIATED · STATUTORY NEGLIGENCE PER SE',
    lab: 'Walk-through audit Mar 15, 2024: bedroom alarm absent (mounting plate only), hallway alarm absent (capped wire), living room alarm battery removed. Kitchen alarm date-stamped 2009 (expired 2019, NFPA 72 §29.8.5). Zero CO alarms detected — combustion appliances present (gas range + furnace).',
    narr: 'Statutory life-safety violation across the unit. Combined with active fire risk (ELEC-001) and combustion appliances, missing alarms create cumulative ignition-detection failure. Negligence per se under CA Evid. Code §669.',
    contra: '⚑ CONTRADICTION: Annual habitability checklist (DFND000701) signed by PM Jan 29, 2023 marks "smoke + CO alarms — TESTED, FUNCTIONAL." Photographic + physical evidence proves alarms were absent on that date.',
    pun: 'CRITICAL', punCls: 'pc', punTxt: 'Falsified safety inspection + 412-day persistent statutory violation + minor occupant = negligence per se with CC §3294 exposure.',
    dmg: '$420,000',
    chain: [
      { date: '2023-01-29', type: 'fail', lbl: 'PM signs falsified annual safety checklist', c: '#dc4f35' },
      { date: '2023-08-12', type: 'noticed', lbl: 'Tenant requests replacement alarms', c: '#22c55e' },
      { date: '2023-08-14', type: 'notice', lbl: 'Written notice — no alarms in sleeping zones', c: '#4b8df8' },
      { date: '2023-08-20', type: 'response', lbl: 'PM: "we will deliver" — never delivered', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO INSTALLATION — 412 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Audit confirms 0/3 alarms in sleeping zones', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'AUD', id: 'AUD-2024-0315-09', bates: 'PLNT000701–705', desc: 'Walk-through audit + alarm count by zone', c: '#facc15' },
      { tp: 'PHO', id: 'PHO-2024-0315-83', bates: 'PLNT000706–709', desc: 'Photographs of empty mounting plates + capped wire', c: '#4b8df8' },
      { tp: 'LOG', id: 'LOG-DFND-701', bates: 'DFND000701', desc: '⚑ PM-signed safety checklist — FALSIFIED', c: '#dc4f35' },
      { tp: 'FED', id: 'FED-NFPA72', bates: 'PLNT000710–712', desc: 'NFPA 72 §29.8.5 expiry analysis (2009 unit)', c: '#dc4f35' },
    ],
  },
  {
    id: 'PEST-001', bates: 'PLNT000801–814', color: '#84cc16', hex: 0x84cc16,
    typeLbl: 'Pest infestation — Norway rat colony (active, multi-generational)', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'Kitchen base cabinets · Bathroom under-sink · adjacent to mold + sewage zones',
    code: 'CA H&S §17920.3(a)(12) · CDC zoonotic protocol',
    threshold: '0 active harborage in habitable unit', found: '47+ fecal pellets · 3 active runways · gnawed romex sheathing',
    area: 'Kitchen + bathroom plumbing penetrations (compounding hazard)',
    pos: [4.4, 0.22, 1.4], gap: 96, reported: '2023-12-08', status: 'UNREMEDIATED · TRAP-ONLY (NO EXCLUSION)',
    lab: 'IPM survey identifies Rattus norvegicus harborage in kitchen + bathroom plumbing chases. 47+ fresh pellets (<72 hr per moisture index). Three established runways with rub marks. Gnawed romex sheathing on 12 AWG branch circuit (cross-references ELEC-001 fire risk). Zoonotic exposure pathway: leptospirosis, hantavirus.',
    narr: 'Active rat colony with multi-generational evidence. PM has set snap traps for 96 days but performed no exclusion or sanitation. Gnawed wiring directly compounds the ELEC-001 fire risk. Bathroom harborage cross-contaminates the MOLD-001 zone via rodent vectors.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: 'Trap-only response without exclusion = constructive failure to abate. Compounding hazards (electrical + biological vector) elevate risk profile.',
    dmg: '$135,000',
    chain: [
      { date: '2023-12-05', type: 'noticed', lbl: 'Tenant reports gnawing sounds + droppings', c: '#22c55e' },
      { date: '2023-12-08', type: 'notice', lbl: 'Written notice + photos to PM', c: '#4b8df8' },
      { date: '2023-12-12', type: 'response', lbl: 'PM places snap traps — no exclusion work', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO EXCLUSION / NO SANITATION — 96 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'IPM survey: active colony + gnawed wiring', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'IPM', id: 'IPM-2024-0315-12', bates: 'PLNT000801–806', desc: 'Integrated pest survey — colony mapping', c: '#84cc16' },
      { tp: 'PHO', id: 'PHO-2024-0315-94', bates: 'PLNT000807–811', desc: 'Photo inventory — runways + gnaw marks on romex', c: '#4b8df8' },
      { tp: 'BIO', id: 'BIO-2024-0315-04', bates: 'PLNT000812–814', desc: 'Zoonotic pathogen risk assessment', c: '#84cc16' },
    ],
  },
  {
    id: 'GAS-001', bates: 'PLNT000901–912', color: '#fb923c', hex: 0xfb923c,
    typeLbl: 'Gas — methane leak at range flex connector + furnace union', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Kitchen (SE) range valve · Utility chase furnace union', code: 'CPC §1212 · 49 CFR §192 · NFPA 54 §7.1.1',
    threshold: 'No detectable leak (combustible gas indicator 0 ppm)', found: '420 ppm at range valve · 180 ppm at furnace union',
    area: '2 active leak points · LEL fraction 8.4% (range)',
    pos: [4.55, 0.95, 2.7], gap: 21, reported: '2024-02-23', status: 'UNREMEDIATED · UTILITY NOT NOTIFIED',
    lab: 'CGI survey: 420 ppm methane at flex connector (range), 180 ppm at furnace union. Soap-bubble test confirms active bubbling at both points. Gas company (PG&E) records show NO leak ticket filed by landlord. Combustible gas + missing CO alarms (LIFE-001) + electrical fire risk (ELEC-001) = compounded ignition + asphyxiation pathway.',
    narr: 'Two active natural-gas leaks. Tenant smelled gas Feb 23 and notified PM same day; PM closed the ticket "no action required." CGI confirms ongoing release. Cross-references LIFE-001 (no CO alarms) and ELEC-001 (active arc risk) — concurrent ignition + detection failure.',
    contra: '⚑ CONTRADICTION: PM ticket (DFND000901) closed with note "tenant misidentified odor — no leak detected." CGI quantitative survey records 420 ppm at the same fixture nine days later.',
    pun: 'CRITICAL', punCls: 'pc', punTxt: 'Active gas leak + falsified diagnostic + non-notification of utility = willful endangerment (CC §3294 + Pub. Util. Code §451).',
    dmg: '$510,000',
    chain: [
      { date: '2024-02-23', type: 'noticed', lbl: 'Tenant smells gas at range — calls PM', c: '#22c55e' },
      { date: '2024-02-23', type: 'notice', lbl: 'Written follow-up + photos to PM', c: '#4b8df8' },
      { date: '2024-02-26', type: 'response', lbl: 'PM ticket closed: "no leak detected"', c: '#dc4f35' },
      { type: 'gap', lbl: 'NO REPAIR · NO UTILITY CALL — 21 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'CGI: 420 ppm range · 180 ppm furnace', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'CGI', id: 'CGI-2024-0315-02', bates: 'PLNT000901–905', desc: 'Combustible gas indicator survey — 2 leak points', c: '#fb923c' },
      { tp: 'PHO', id: 'PHO-2024-0315-110', bates: 'PLNT000906–909', desc: 'Soap-bubble test photo + video evidence', c: '#4b8df8' },
      { tp: 'LOG', id: 'LOG-DFND-901', bates: 'DFND000901', desc: '⚑ PM closed-ticket "no leak" — CONTRADICTED', c: '#dc4f35' },
      { tp: 'SUB', id: 'SUB-PGE-2024', bates: 'PLNT000910–912', desc: 'PG&E subpoena: no leak ticket ever filed', c: '#8b5cf6' },
    ],
  },
  {
    id: 'EGRS-001', bates: 'PLNT001001–1010', color: '#f472b6', hex: 0xf472b6,
    typeLbl: 'Egress — bedroom window blocked + exterior security bars without release', sev: 'IMMINENT HAZARD', sevCls: 'si',
    room: 'Bedroom (NE) — sole egress window · minor child sleeping zone',
    code: 'CRC §R310 · CFC §1031 · CA H&S §17920.3(a)(2)',
    threshold: 'Net clear opening 5.7 sq ft · sill ≤44" · interior release required',
    found: 'Opening 4.1 sq ft · sill 52" · welded steel bars · NO interior release',
    area: 'Sole egress for sleeping room',
    pos: [2.4, 1.75, -3.95], gap: 287, reported: '2023-06-02', status: 'UNREMEDIATED · BARRED EGRESS',
    lab: 'Field measurement: net clear opening 4.1 sq ft (28% below CRC §R310.2.1). Sill height 52" (8" above max). Exterior security bars (welded, not bolted) installed without code-required interior quick-release per CFC §1031.4. Combined with GAS-001 + LIFE-001: occupants cannot self-rescue from a sleeping room with active ignition + asphyxiation hazards and no alarm.',
    narr: 'Sole bedroom egress is non-compliant in opening area, sill height, and bar release. Child sleeps in this room. The compounding interaction with gas leak, missing alarms, and electrical fire risk creates a mathematically foreseeable trapped-occupant scenario.',
    contra: null,
    pun: 'CRITICAL', punCls: 'pc', punTxt: '287 days non-conforming + child occupant + cumulative life-safety stack = willful disregard (CC §3294).',
    dmg: '$365,000',
    chain: [
      { date: '2023-06-02', type: 'noticed', lbl: 'Tenant requests bar release / replacement', c: '#22c55e' },
      { date: '2023-06-02', type: 'notice', lbl: 'Written notice citing CRC §R310', c: '#4b8df8' },
      { date: '2023-06-15', type: 'response', lbl: 'PM: "bars stay — security policy"', c: '#dc4f35' },
      { type: 'gap', lbl: 'NO MODIFICATION — 287 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Field measurement confirms 3-axis non-compliance', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'MEA', id: 'MEA-2024-0315-14', bates: 'PLNT001001–1005', desc: 'Field opening + sill height measurement record', c: '#f472b6' },
      { tp: 'PHO', id: 'PHO-2024-0315-128', bates: 'PLNT001006–1008', desc: 'Photographs of welded bars + missing release', c: '#4b8df8' },
      { tp: 'EML', id: 'EML-PM-2023-0615', bates: 'DFND000615', desc: 'PM email refusing modification — "security policy"', c: '#dc4f35' },
      { tp: 'STR', id: 'STR-CRC-R310', bates: 'PLNT001009–1010', desc: 'CRC §R310 / CFC §1031 compliance memo', c: '#dc4f35' },
    ],
  },
  {
    id: 'RAD-001', bates: 'PLNT001101–1110', color: '#a3e635', hex: 0xa3e635,
    typeLbl: 'Indoor radon — sub-slab infiltration through cracked living-room slab', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'Living room (SW) · ground-floor concentration zone', code: 'EPA 402-R-92-004 · CA DPH IAQ',
    threshold: '4.0 pCi/L (EPA action level)', found: '11.8 pCi/L (90-day CRM avg) — 2.95× action level',
    area: 'Whole-unit equilibrium · highest at slab crack near CRACK-001',
    pos: [-0.5, 0.10, 3.6], gap: 64, reported: '2024-01-11', status: 'UNREMEDIATED · NO MITIGATION',
    lab: 'Continuous radon monitor (CRM) deployed Dec 16, 2023 – Mar 15, 2024 — 90-day average 11.8 pCi/L (EPA action: 4.0). Working-level equivalent risk: ~21 lung-cancer deaths per 1,000. Source confirmed via grab-sample at slab crack feeding from CRACK-001. Mitigation system (active sub-slab depressurization) never installed.',
    narr: 'Long-term radon at 2.95× EPA action level. Cracked slab provides direct soil-gas pathway. PM was given the CRM report Jan 11 and took no action. Cumulative carcinogen exposure for the minor child compounds the LEAD-001 federal exposure profile.',
    contra: null,
    pun: 'HIGH', punCls: 'ph', punTxt: 'Documented carcinogen exposure + 64-day non-response after written CRM data = willful indifference.',
    dmg: '$245,000',
    chain: [
      { date: '2023-12-16', type: 'noticed', lbl: 'Tenant deploys CRM (concern after CRACK-001)', c: '#22c55e' },
      { date: '2024-01-11', type: 'notice', lbl: 'CRM 30-day report delivered to PM', c: '#4b8df8' },
      { date: '2024-01-18', type: 'response', lbl: 'PM: "radon is naturally occurring"', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO MITIGATION — 64 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: '90-day CRM average finalized at 11.8 pCi/L', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'CRM', id: 'CRM-2024-0315-01', bates: 'PLNT001101–1106', desc: 'Continuous radon monitor — 90-day record', c: '#a3e635' },
      { tp: 'AIR', id: 'AIR-2024-0315-03', bates: 'PLNT001107–1108', desc: 'Grab-sample at slab crack — 18.4 pCi/L peak', c: '#a78bfa' },
      { tp: 'EML', id: 'EML-PM-2024-0118', bates: 'DFND000711', desc: 'PM email dismissing CRM report', c: '#f59e0b' },
      { tp: 'STR', id: 'STR-EPA-402', bates: 'PLNT001109–1110', desc: 'EPA action-level + mitigation standard memo', c: '#dc4f35' },
    ],
  },
  {
    id: 'NOIS-001', bates: 'PLNT001201–1208', color: '#c084fc', hex: 0xc084fc,
    typeLbl: 'Noise — chronic mechanical hum + impact transfer (HVAC + upstairs)', sev: 'SIGNIFICANT', sevCls: 'ss',
    room: 'Bedroom (NE) · Living room — sustained nighttime exposure',
    code: 'CA Civ. §1927 (quiet enjoyment) · HUD 24 CFR §51 · Local NMC §8.32',
    threshold: 'Nighttime Leq 45 dBA · Lmax 60 dBA', found: 'Leq 58 dBA · Lmax 74 dBA · 22:00–06:00 · 31 nights logged',
    area: 'Sleeping zones · 31-night dosimetry sample',
    pos: [1.6, 1.1, -2.5], gap: 73, reported: '2024-01-02', status: 'UNREMEDIATED · ROOT CAUSE: HVAC-001',
    lab: '31-night Class-1 dosimeter deployment: nighttime Leq 58 dBA (threshold 45), Lmax 74 dBA (threshold 60). Spectral analysis: 60 Hz harmonic from failing HVAC compressor + impact transfer from upstairs unit. Sleep-disruption score (Pittsburgh Index) elevated for both adults; pediatric impact under separate evaluation.',
    narr: 'Chronic nighttime noise above HUD and local thresholds. Primary source is the same failing HVAC system at root of HVAC-001, compounding habitability injury. Sleep-disruption documented dosimetrically rather than anecdotally.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: 'Quantified threshold exceedance + 73-day inaction + shared-cause with HVAC-001 = constructive knowledge.',
    dmg: '$78,000',
    chain: [
      { date: '2023-12-29', type: 'noticed', lbl: 'Tenant logs first sleep disruption', c: '#22c55e' },
      { date: '2024-01-02', type: 'notice', lbl: 'Written notice + initial dB readings to PM', c: '#4b8df8' },
      { date: '2024-01-08', type: 'response', lbl: 'PM: "within normal range"', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO ABATEMENT — 73 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: '31-night dosimetry confirms exceedance', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'DOS', id: 'DOS-2024-0315-05', bates: 'PLNT001201–1205', desc: 'Class-1 noise dosimeter — 31-night record', c: '#c084fc' },
      { tp: 'LAB', id: 'LAB-FFT-01', bates: 'PLNT001206–1207', desc: 'FFT spectral analysis — 60 Hz HVAC signature', c: '#22c55e' },
      { tp: 'EML', id: 'EML-PM-2024-0108', bates: 'DFND000812', desc: 'PM dismissal email — "within normal range"', c: '#f59e0b' },
      { tp: 'MED', id: 'MED-PSQI-01', bates: 'PLNT001208', desc: 'Pittsburgh Sleep Quality Index — elevated', c: '#e060a0' },
    ],
  },
  {
    id: 'ADA-001', bates: 'PLNT001301–1308', color: '#60a5fa', hex: 0x60a5fa,
    typeLbl: 'Accessibility — refused reasonable accommodation (grab bars + lever hardware)', sev: 'SIGNIFICANT', sevCls: 'ss',
    room: 'Bathroom (NW) + unit-wide door hardware', code: 'FHA §3604(f) · CA FEHA §12927 · ADA Title III (common areas)',
    threshold: 'Reasonable accommodation timely granted', found: 'Documented refusal · 154-day delay · no interactive process',
    area: 'Bathroom + 4 interior doors · 1 disabled occupant',
    pos: [-3.4, 1.2, -2.4], gap: 154, reported: '2023-10-12', status: 'REFUSED · IN VIOLATION',
    lab: 'Tenant submitted FHA §3604(f)(3)(B) accommodation request Oct 12, 2023 with treating-physician letter for grab bars (toilet + tub) and lever hardware (knob → lever) for an occupant with documented mobility impairment. PM denied in writing Oct 26 citing "aesthetics," failed to engage interactive process, and offered no alternative.',
    narr: 'FHA / FEHA reasonable-accommodation request refused without interactive process. Modification cost <$400; tenant offered to pay. Refusal triggers HUD-administrative + private-cause-of-action exposure independent of habitability claims.',
    contra: '⚑ CONTRADICTION: PM denial letter (DFND000812) cites "no documented disability." Treating-physician letter (PLNT001302) was attached to the original request and acknowledged in PM intake email Oct 14.',
    pun: 'HIGH', punCls: 'ph', punTxt: 'Refusal with falsified rationale + 154-day persistence = FHA willful violation (statutory damages + fees).',
    dmg: '$155,000',
    chain: [
      { date: '2023-10-12', type: 'notice', lbl: 'FHA accommodation request + physician letter', c: '#4b8df8' },
      { date: '2023-10-14', type: 'response', lbl: 'PM intake email — acknowledges receipt', c: '#f59e0b' },
      { date: '2023-10-26', type: 'response', lbl: 'PM written denial — "no documented disability"', c: '#dc4f35' },
      { type: 'gap', lbl: 'NO INTERACTIVE PROCESS — 154 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Status: still refused, hardware unchanged', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'LTR', id: 'LTR-FHA-2023-1012', bates: 'PLNT001301', desc: 'FHA §3604(f) reasonable-accommodation request', c: '#f59e0b' },
      { tp: 'MED', id: 'MED-PHYS-2023-10', bates: 'PLNT001302–1304', desc: 'Treating-physician disability letter', c: '#e060a0' },
      { tp: 'LOG', id: 'LOG-DFND-812', bates: 'DFND000812', desc: '⚑ PM denial letter — CONTRADICTED', c: '#dc4f35' },
      { tp: 'FED', id: 'FED-FHA-3604', bates: 'PLNT001305–1308', desc: 'FHA / FEHA exposure analysis + damages model', c: '#dc4f35' },
    ],
  },
  {
    id: 'WIN-001', bates: 'PLNT001401–1408', color: '#fda4af', hex: 0xfda4af,
    typeLbl: 'Glazing — single-pane sash w/ lead paint sill + air infiltration (5 windows)', sev: 'SIGNIFICANT', sevCls: 'ss',
    room: 'Bedroom · Living room · Kitchen — 5 of 6 unit windows',
    code: 'CA T24 §110.6 · ASTM E283 · 40 CFR §745.65 (RRP)',
    threshold: 'Air infiltration ≤0.30 cfm/ft² · sill paint intact', found: '1.8–2.4 cfm/ft² · friable lead-paint sill chipping (overlap LEAD-001)',
    area: '5 windows · ~62 linear ft of weatherstrip + sill',
    pos: [-3.3, 1.6, -3.95], gap: 198, reported: '2023-08-30', status: 'UNREMEDIATED',
    lab: 'Blower-door zonal pressurization: 1.8–2.4 cfm/ft² (T24 limit 0.30). XRF on sash sills positive at 1.6–2.1 mg/cm² overlapping LEAD-001 zone. Any disturbance for re-glazing triggers EPA RRP (40 CFR §745.65) — landlord is not RRP-certified, creating a self-imposed scope-of-work block.',
    narr: 'Five exterior windows are 6–8× T24 infiltration. Sashes are pre-1978 wood with deteriorating lead paint sills, geometrically expanding the LEAD-001 hazard surface. Repair pathway is gated by EPA RRP certification the landlord lacks.',
    contra: null,
    pun: 'MEDIUM', punCls: 'pm', punTxt: '198-day inaction + RRP-gated repair path + child occupant overlap = constructive escalation of LEAD-001.',
    dmg: '$112,000',
    chain: [
      { date: '2023-08-28', type: 'noticed', lbl: 'Tenant reports cold drafts + paint chips', c: '#22c55e' },
      { date: '2023-08-30', type: 'notice', lbl: 'Written notice w/ photos to PM', c: '#4b8df8' },
      { date: '2023-09-12', type: 'response', lbl: 'PM: "weatherstripping next season"', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO REMEDIATION — 198 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Blower-door + XRF survey of all 6 windows', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'BLD', id: 'BLD-2024-0315-02', bates: 'PLNT001401–1404', desc: 'Blower-door zonal infiltration record', c: '#8b5cf6' },
      { tp: 'XRF', id: 'XRF-2024-0315-04', bates: 'PLNT001405–1407', desc: 'XRF — sill paint 1.6–2.1 mg/cm² (5 windows)', c: '#e060a0' },
      { tp: 'FED', id: 'FED-RRP-745', bates: 'PLNT001408', desc: 'EPA RRP §745.65 certification gap memo', c: '#dc4f35' },
    ],
  },
  {
    id: 'VENT-001', bates: 'PLNT001501–1510', color: '#2dd4bf', hex: 0x2dd4bf,
    typeLbl: 'Ventilation — bathroom + kitchen exhaust non-functional (ASHRAE 62.2 fail)', sev: 'MATERIAL BREACH', sevCls: 'sm',
    room: 'Bathroom (NW) + Kitchen (SE) range hood', code: 'ASHRAE 62.2 §5 · CMC §403 · CA T24 §150.0(o)',
    threshold: 'Bath ≥50 cfm intermittent · Range hood ≥100 cfm vented outdoors',
    found: 'Bath fan: 0 cfm (motor seized) · Range hood: recirculating only (no duct)',
    area: 'Whole-unit IAQ — root-cause amplifier of MOLD-001 + RAD-001 + GAS-001',
    pos: [-2.4, 2.95, -2.6], gap: 89, reported: '2023-12-17', status: 'UNREMEDIATED · COMPOUND AMPLIFIER',
    lab: 'Anemometer at bath fan grille: 0 cfm (motor seized, dust-bound impeller). Range hood: ductless recirculating with carbon filter last replaced per inspection ≥5 yr ago — fails CMC §403 outdoor-exhaust requirement. CO₂ tracer decay: ACH 0.18 (T24 minimum 0.35) — chronic under-ventilation amplifies mold spore load, radon equilibrium, and combustion-product accumulation.',
    narr: 'No functional exhaust in bathroom; kitchen hood recirculates rather than vents outdoors. Tracer-gas measurement confirms whole-unit ACH at half the code minimum. This is the single largest compounding multiplier across MOLD, RAD, and GAS defects.',
    contra: null,
    pun: 'HIGH', punCls: 'ph', punTxt: 'Compound-amplifier role + 89-day inaction + measurable amplification of three IH defects = aggravated CC §3294 exposure.',
    dmg: '$165,000',
    chain: [
      { date: '2023-12-15', type: 'noticed', lbl: 'Tenant reports fan dead + cooking-smoke buildup', c: '#22c55e' },
      { date: '2023-12-17', type: 'notice', lbl: 'Written notice to PM', c: '#4b8df8' },
      { date: '2023-12-22', type: 'response', lbl: 'PM: "scheduling" — no follow-up', c: '#f59e0b' },
      { type: 'gap', lbl: 'NO REPAIR — 89 DAYS', c: '#dc4f35' },
      { date: '2024-03-15', type: 'inspect', lbl: 'Anemometer + CO₂ tracer survey complete', c: '#8b5cf6' },
    ],
    evidence: [
      { tp: 'AIR', id: 'AIR-2024-0315-04', bates: 'PLNT001501–1505', desc: 'Anemometer + CO₂ tracer-decay ACH record', c: '#a78bfa' },
      { tp: 'PHO', id: 'PHO-2024-0315-141', bates: 'PLNT001506–1508', desc: 'Borescope: seized fan motor + ductless hood', c: '#4b8df8' },
      { tp: 'STR', id: 'STR-ASHRAE-62', bates: 'PLNT001509–1510', desc: 'ASHRAE 62.2 / CMC §403 compliance memo', c: '#dc4f35' },
    ],
  },
];

export const TYPE_COLORS: Record<string, string> = {
  LAB: '#22c55e', PHO: '#4b8df8', LTR: '#f59e0b', EML: '#f59e0b',
  LOG: '#dc4f35', RDR: '#4b8df8', BOR: '#22c55e', INV: '#8b5cf6',
  STR: '#dc4f35', XRF: '#e060a0', DIS: '#dc4f35', MED: '#e060a0',
  BLD: '#8b5cf6', FED: '#dc4f35', SUB: '#8b5cf6',
  PLM: '#a78bfa', AIR: '#a78bfa', IRT: '#fb7185',
  BIO: '#38bdf8', ATP: '#38bdf8', AUD: '#facc15', IPM: '#84cc16',
  CGI: '#fb923c', MEA: '#f472b6', CRM: '#a3e635', DOS: '#c084fc',
};